include: ../../analysis_options.yaml

analyzer:
  errors:
    inference_failure_on_function_invocation: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app.*.dart"
    - "**/*.form.dart"
    - "**/*.mocks.dart"
    - build/**
    - web/**

linter:
  rules:
    public_member_api_docs: false
