name: analytics
description: analytics package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  firebase_analytics: ^11.3.5
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  logger:
  mixpanel_flutter: ^2.3.3
  responsive_builder: ^0.7.1
  stacked: ^3.4.3
  stacked_services: ^1.6.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito:
  stacked_generator: ^1.5.2
  very_good_analysis: ^5.1.0

dependency_overrides:
  meta: ^1.15.0
    
flutter:
  uses-material-design: true
