name: file_upload
description: File Upload module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  archive: ^3.4.5
  flutter:
    sdk: flutter

  file_picker: ^5.5.0
  dio: ^5.3.2
  http_parser: ^4.0.2
  mime: ^1.0.4
  mime_type: ^1.0.0
  file_icon: ^1.0.0
  surrealdb_wasm:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.fluwix.file_upload
    iosBundleIdentifier: com.fluwix.fileUpload
