name: rag
description: RAG.WTF App.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  file_upload:
    path: file_upload
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  mocktail: ^1.0.0
  stacked_generator: ^1.3.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
