name: rag
description: RAG.WTF App.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies: 
  archive: 
    path: archive
  dio: 
    path: dio
  chat:
    path: chat
  document:
    path: document
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  rag_console:
    path: rag_console
  settings:
    path: settings
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  stacked_themes: ^0.3.12
  surrealdb_wasm: ^0.7.0+3

dev_dependencies:
  analyzer: ^6.3.0
  build_runner: ^2.4.5
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  mocktail: ^1.0.0
  stacked_generator: ^1.5.2
  very_good_analysis: ^5.1.0

dependency_overrides:
  meta: ^1.11.0

flutter:
  assets:
    - assets/
  uses-material-design: true
  import 'package:archive/archive.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:rag/app/app.router.dart';
import 'package:rag/l10n/l10n.dart';
import 'package:rag/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:rag/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:rag/ui/views/home/home_view.dart';
import 'package:rag/ui/views/startup/startup_view.dart';
import 'package:settings/settings.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:stacked_themes/stacked_themes.dart';
import 'package:surrealdb_wasm/surrealdb_wasm.dart;
