name: rag
description: RAG.WTF App.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  archive: ^3.6.1
  chat:
    path: chat
  confirm_dialog: ^1.0.3
  database:
    path: database  
  dio: ^5.6.0
  document:
    path: document
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2    
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  rag_console:
    path: rag_console
  settings:
    path: settings
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  stacked_themes: ^0.3.13
  surrealdb_js: ^1.0.0-beta.20+4
  surrealdb_wasm: ^1.0.0-beta.16+11

dev_dependencies:
  analyzer: ^6.5.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  mocktail: ^1.0.0
  stacked_generator: ^2.0.0-pre.1
  very_good_analysis: ^6.0.0

dependency_overrides:
  meta: ^1.15.0
  very_good_infinite_list: 
    path: very_good_infinite_list

flutter:
  assets:
    - assets/
  uses-material-design: true
  generate: true
