name: rag
description: RAG.WTF App.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  archive: ^3.6.1
  chat:
    path: packages/chat
  database:
    path: packages/database  
  dio: ^5.6.0
  document:
    path: packages/document
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_zoom_drawer: ^3.2.0
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  rag_console:
    path: packages/rag_console
  settings:
    path: packages/settings
  share_plus: ^10.0.2
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  stacked_themes: ^0.3.13
  surrealdb_js: ^1.0.1+7
  surrealdb_wasm: ^1.0.1+15
  ui:
    path: packages/ui
  url_launcher: ^6.3.0

dev_dependencies:
  analyzer: ^6.5.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  melos: ^6.2.0    
  mockito: ^5.4.1
  mocktail: ^1.0.0
  stacked_generator: ^2.0.0-pre.1
  very_good_analysis: ^6.0.0

dependency_overrides:
  meta: ^1.15.0
  #surrealdb_wasm:
  #  path: ../surrealdb_wasm
  very_good_infinite_list: 
    path: packages/very_good_infinite_list

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  generate: true
