name: rag
description: RAG.WTF App.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

workspace:
  - packages/analytics
  - packages/chat
  - packages/console
  - packages/database
  - packages/document
  - packages/flutter_console
  - packages/rag_console
  - packages/settings
  - packages/stacked_package_template
  - packages/ui
  - packages/very_good_infinite_list

dependencies:
  analytics:
    path: packages/analytics
  archive: ^4.3.0
  chat:
    path: packages/chat
  database:
    path: packages/database  
  dio: ^5.11.1
  document:
    path: packages/document
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  flutter_zoom_drawer: ^3.2.0
  intl: ^0.20.3
  logger: ^2.8.0
  package_info_plus: ^10.2.1
  rag_console:
    path: packages/rag_console
  settings:
    path: packages/settings
  share_plus: ^13.3.0
  stacked: ^3.5.0
  stacked_services: ^1.6.0
  stacked_themes: ^0.3.15
  surrealdb_js: ^1.1.0+9
  surrealdb_wasm: ^1.1.0+16
  ui:
    path: packages/ui
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.16.1
  flutter_test:
    sdk: flutter
  melos: ^8.8.0    
  mockito: ^5.8.1
  mocktail: ^1.0.5
  stacked_generator: ^2.0.4
  very_good_analysis: ^11.0.0

dependency_overrides:
  meta: ^1.19.0
  #surrealdb_wasm:
  #  path: ../surrealdb_wasm

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  generate: true

melos:
  scripts:
    analyze:
      run: dart run melos exec -- flutter analyze .
      description: Run `flutter analyze` for all packages

    test:
      run: dart run melos exec -- flutter test
      description: Run `flutter test` for all packages

    build_dev:
      run: flutter clean;flutter build web --release --no-tree-shake-icons --target lib/main_development.dart --dart-define-from-file=.env.dev --pwa-strategy=none
      description: Build app for web in development flavor

    build_prod:
      run: flutter clean;flutter build web --release --no-tree-shake-icons --target lib/main_production.dart --dart-define-from-file=.env.prod --no-source-maps --pwa-strategy=none
      description: Build app for web in production flavor

    build_stg:
      run: flutter clean;flutter build web --release --no-tree-shake-icons --target lib/main_staging.dart --dart-define-from-file=.env.stg --pwa-strategy=none
      description: Build app for web in staging flavor

    generate_packages:
      run: dart run melos exec --order-dependents -- dart run build_runner build --delete-conflicting-outputs
      description: Run code generation for all packages
      packageFilters:
        scope:
          - analytics
          - database
          - settings
          - document
          - chat
          - rag_console
          - stacked_package_template

    generate:
      run: dart run build_runner build --delete-conflicting-outputs
      description: Run code generation for project

    start_server:
      run: python -m http.server 8000 --directory ./build/web
      description: Start a local server for the web build

    start_surreal:
      run: sudo docker run --rm --pull always -p 7000:8000 -v ~/surrealdb_data:/surrealdb_data surrealdb/surrealdb:latest start --log trace -A --user root --pass root surrealkv://surrealdb_data/test.db
      description: Start SurrealDB in a Docker container

    ci_integration_test:
      run: |
        docker run --rm --pull always -p 8000:8000 --name surrealdb surrealdb/surrealdb:latest start memory -A --user root --pass root &
        melos exec --concurrency 1 -- flutter drive --driver=test_driver/integration_test.dart --target integration_test/all_tests.dart -d web-server --release --browser-name=chrome
        docker container stop surrealdb
      description: Run integration tests for all packages in CI environment
      packageFilters:
        dirExists: integration_test

    local_integration_test:
      run: |
        docker run --rm --pull always -p 8000:8000 --name surrealdb surrealdb/surrealdb:latest start memory -A --user root --pass root &
        melos exec --concurrency 1 -- flutter drive --driver=test_driver/integration_test.dart --target integration_test/all_tests.dart -d chrome --debug
        docker container stop surrealdb
      description: Run integration tests for all packages locally
      packageFilters:
        dirExists: integration_test

    update_version:
      run: |
        VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2)
        NEW_VERSION="$VERSION+$GITHUB_RUN_NUMBER"
        sed -i "s/version: $VERSION/version: $NEW_VERSION/g" pubspec.yaml
      description: Update version in pubspec.yaml with GitHub run number

    run:
      run: flutter run --flavor development --target lib/main_development.dart --dart-define-from-file .env.dev
      description: Run app in development flavor
