name: chat
description: chat package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  archive: ^3.4.10
  avatar_brick: ^0.2.0
  dio: ^5.4.0
  document:
    path: ../document
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_schema: ^5.1.3
  logger:
  markdown_widget: ^2.3.2+3
  responsive_builder: ^0.7.0
  scroll_indicator: ^0.0.3
  settings:
    path: ../settings
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  surrealdb_wasm: ^0.7.0+3
  ulid: ^2.0.0
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito:
  stacked_generator: ^1.5.2
  very_good_analysis: ^5.1.0

dependency_overrides:
  meta: ^1.11.0
