name: settings
description: Settings package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  database: 
    path: ../database
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2  
  freezed_annotation: ^2.4.4
  fzregex: ^2.0.0
  json_annotation: ^4.9.0
  json_schema: ^5.2.0
  logger:
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  surrealdb_js: ^1.0.0-beta.20+5
  surrealdb_wasm: ^1.0.0-beta.16+13
  ulid: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.1
  stacked_generator: ^2.0.0-pre.1
  very_good_analysis: ^6.0.0

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true
