name: settings
description: Settings package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  env_reader: ^2.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  json_schema: ^5.1.3
  logger:
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  surrealdb_wasm: ^0.7.0+3
  ulid: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.1
  stacked_generator: ^1.5.2
  very_good_analysis: ^5.1.0

dependency_overrides:
  meta: ^1.11.0

flutter:
  assets:
    - assets/
