include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  errors:
    inference_failure_on_function_invocation: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app.*.dart"
    - "**/*.form.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    public_member_api_docs: false
