// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8axT9hCEXYi1yLTs25Km5EVlC5h5WD7E',
    appId: '1:1082255562580:web:434a1fdb1e8ee7782b5ac1',
    messagingSenderId: '1082255562580',
    projectId: 'rag-dev-8fbc0',
    authDomain: 'rag-dev-8fbc0.firebaseapp.com',
    storageBucket: 'rag-dev-8fbc0.firebasestorage.app',
    measurementId: 'G-LTJK04YZMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD68dY0ajfqiS1mSLEqJsALCFeRVdr0bO8',
    appId: '1:1082255562580:android:192464c79f1086852b5ac1',
    messagingSenderId: '1082255562580',
    projectId: 'rag-dev-8fbc0',
    storageBucket: 'rag-dev-8fbc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfV4-mlqTMjfeVE_eDUTKaQD05rdvdA38',
    appId: '1:1082255562580:ios:9ea77b5623e9fc752b5ac1',
    messagingSenderId: '1082255562580',
    projectId: 'rag-dev-8fbc0',
    storageBucket: 'rag-dev-8fbc0.firebasestorage.app',
    iosBundleId: 'wtf.rag.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfV4-mlqTMjfeVE_eDUTKaQD05rdvdA38',
    appId: '1:1082255562580:ios:9ea77b5623e9fc752b5ac1',
    messagingSenderId: '1082255562580',
    projectId: 'rag-dev-8fbc0',
    storageBucket: 'rag-dev-8fbc0.firebasestorage.app',
    iosBundleId: 'wtf.rag.app.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8axT9hCEXYi1yLTs25Km5EVlC5h5WD7E',
    appId: '1:1082255562580:web:ec8c1fb0972e90e12b5ac1',
    messagingSenderId: '1082255562580',
    projectId: 'rag-dev-8fbc0',
    authDomain: 'rag-dev-8fbc0.firebaseapp.com',
    storageBucket: 'rag-dev-8fbc0.firebasestorage.app',
    measurementId: 'G-RX02BLD1N2',
  );
}
