// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApSiH55ILXE8KAaT5OC-rTYVVaS43Rpvc',
    appId: '1:58905576586:web:4c8369e1d5a88811af1973',
    messagingSenderId: '58905576586',
    projectId: 'rag-stg',
    authDomain: 'rag-stg.firebaseapp.com',
    storageBucket: 'rag-stg.firebasestorage.app',
    measurementId: 'G-19DQJ6G1S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPEQcdeHBoqONRq-ZLRDbG16u5R0Y_7g',
    appId: '1:58905576586:android:786360acb48e7b07af1973',
    messagingSenderId: '58905576586',
    projectId: 'rag-stg',
    storageBucket: 'rag-stg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMTz5wqxQsF4o8PaPQaFL2J6HB2yb-jJI',
    appId: '1:58905576586:ios:7b17578efad2b340af1973',
    messagingSenderId: '58905576586',
    projectId: 'rag-stg',
    storageBucket: 'rag-stg.firebasestorage.app',
    iosBundleId: 'wtf.rag.app.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMTz5wqxQsF4o8PaPQaFL2J6HB2yb-jJI',
    appId: '1:58905576586:ios:7b17578efad2b340af1973',
    messagingSenderId: '58905576586',
    projectId: 'rag-stg',
    storageBucket: 'rag-stg.firebasestorage.app',
    iosBundleId: 'wtf.rag.app.stg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApSiH55ILXE8KAaT5OC-rTYVVaS43Rpvc',
    appId: '1:58905576586:web:1c4b7c0d9dad14d2af1973',
    messagingSenderId: '58905576586',
    projectId: 'rag-stg',
    authDomain: 'rag-stg.firebaseapp.com',
    storageBucket: 'rag-stg.firebasestorage.app',
    measurementId: 'G-8NT7BHJKD6',
  );

}