// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Wljv7Cw-tGss5F1atGyuWIZ9eWXPTBs',
    appId: '1:900976630231:web:f1d6f4ad0e46e23c181392',
    messagingSenderId: '900976630231',
    projectId: 'rag-prod',
    authDomain: 'rag-prod.firebaseapp.com',
    storageBucket: 'rag-prod.firebasestorage.app',
    measurementId: 'G-H0GJ5SLEG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRszgiLDZk95GnJ6hx-2jcri88pe_DlY',
    appId: '1:900976630231:android:e0901384193cc050181392',
    messagingSenderId: '900976630231',
    projectId: 'rag-prod',
    storageBucket: 'rag-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWd6Pu5VSxCpM4a697gPoqVuQ2LAJD4zQ',
    appId: '1:900976630231:ios:f4b6c5f95ef35569181392',
    messagingSenderId: '900976630231',
    projectId: 'rag-prod',
    storageBucket: 'rag-prod.firebasestorage.app',
    iosBundleId: 'wtf.rag.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWd6Pu5VSxCpM4a697gPoqVuQ2LAJD4zQ',
    appId: '1:900976630231:ios:f4b6c5f95ef35569181392',
    messagingSenderId: '900976630231',
    projectId: 'rag-prod',
    storageBucket: 'rag-prod.firebasestorage.app',
    iosBundleId: 'wtf.rag.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Wljv7Cw-tGss5F1atGyuWIZ9eWXPTBs',
    appId: '1:900976630231:web:86fa0c028623624a181392',
    messagingSenderId: '900976630231',
    projectId: 'rag-prod',
    authDomain: 'rag-prod.firebaseapp.com',
    storageBucket: 'rag-prod.firebasestorage.app',
    measurementId: 'G-DV3V67ESPC',
  );

}