name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Build and deploy
        run: dart build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: build/

      - name: Deploy to production
        uses: some-deployment-action@v1
        with:
          environment: production
          token: ${{ secrets.PRODUCTION_TOKEN }}
