name: document
description: document package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  surrealdb_wasm:
  archive: ^3.4.10
  dio: ^5.4.0
  file_icon: ^1.0.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  json_schema: ^5.1.3
  logger:
  mime: ^1.0.4
  mime_type: ^1.0.0
  responsive_builder: ^0.7.0
  settings:
    path: ../settings
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  surrealdb_wasm: #^0.7.0+3
    path: ../../surrealdb_wasm
  ulid: ^2.0.0
  very_good_infinite_list: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito:
  stacked_generator: ^1.5.2
  very_good_analysis: ^5.1.0

dependency_overrides:
  js: ^0.7.0
  meta: ^1.11.0
