name: document
description: document package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  archive: ^3.6.1
  database:
    path: ../database
  dio: ^5.6.0
  file_icon: ^1.0.0
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2  
  freezed_annotation: ^2.4.1
  http_parser: ^4.0.2
  json_annotation: ^4.9.0
  logger:
  mime: ^1.0.5
  mime_type: ^1.0.0
  mutex: ^3.1.0
  responsive_builder: ^0.7.0
  settings:
    path: ../settings
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  surrealdb_js: ^1.0.0-beta.20+5
  surrealdb_wasm: ^1.0.0-beta.16+13
  ui:
    path: ../ui
  ulid: ^2.0.0
  very_good_infinite_list: ^0.7.1
  

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito:
  stacked_generator: 2.0.0-pre.1
  very_good_analysis: ^6.0.0

dependency_overrides:
  meta: ^1.15.0
  #surrealdb_js:
  #  path: ../../surrealdb_js
  
flutter:
  uses-material-design: true
