name: Deploy to Netlify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Generate Codes
        run: |
          chmod +x ./database/generate.sh && cd database && ./generate.sh && cd ..
          chmod +x ./document/generate.sh && cd document && ./generate.sh && cd ..
          chmod +x ./chat/generate.sh && cd chat && ./generate.sh && cd ..
          chmod +x ./rag_console/generate.sh && cd rag_console && ./generate.sh && cd ..
          chmod +x ./settings/generate.sh && cd settings && ./generate.sh && cd ..

      - name: Create .env file
        run: echo "${{ secrets.DOT_ENV_FILE }}" > .env

      - name: Update GITHUB_RUN_NUMBER to version
        run: ./update_version.sh
        
      - name: Flutter Build
        run: >
          flutter build web 
          --web-renderer html 
          --release 
          --no-tree-shake-icons 
          --target lib/main_production.dart
          --dart-define-from-file=.env

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./build/web"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
