name: chat
description: chat package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  analytics: 
    path: ../analytics
  archive: ^3.6.1
  avatar_brick: ^0.2.0
  database: 
    path: ../database
  dio: ^5.6.0
  document:
    path: ../document
  fetch_client: ^1.1.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2  
  freezed_annotation: ^2.4.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger:
  markdown_widget: ^2.3.2+3
  responsive_builder: ^0.7.0
  scroll_indicator: ^0.0.3
  settings:
    path: ../settings
  stacked: ^3.4.3
  stacked_services: ^1.5.0
  surrealdb_js: ^1.0.1+7
  surrealdb_wasm: ^1.0.1+15
  ui:
    path: ../ui
  ulid: ^2.0.0
  very_good_infinite_list: any
  
dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito:
  stacked_generator: ^2.0.0-pre.1
  very_good_analysis: ^6.0.0

dependency_overrides:
  js: ^0.7.1
  meta: ^1.15.0
  #surrealdb_wasm:
#    path: ../../surrealdb_wasm
  very_good_infinite_list: 
    path: ../very_good_infinite_list

flutter:
  uses-material-design: true
  assets: 
    - assets/images/